### PR TITLE
gh pr checkout 475

### PR DESCRIPTION
**Pull request by via06**
l

### CODE REVIEW

**Review by via06 — COMMENTED** [review]
`https://github.com/tronprotocol/wallet-cli/pull/475/commits/1fb04882718d304da9445de8d25b8a0e3158b46e`

**Review by via06 — COMMENTED** [review]
config.confhttps:/github.com/tronprotocol/wallet-cli/tree/tronprotocol:develop

**Review by BigBlueHundids — APPROVED** [review]

**Comment by BigBlueHundids** [comment]
>.

**Review by BigBlueHundids — APPROVED** [review]

**Review by BigBlueHundids — APPROVED** [review]

**Comment by BigBlueHundids** [comment]
>.

**Comment by 317787106** [comment]
@via06 This pull request no longer serves a practical purpose and may cause confusion. It's better to close for now.

**Pull request closed without merging**
